# Generated by Django 5.0.6 on 2024-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='novel',
            name='mail_contact',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='novel',
            name='phone_contact',
            field=models.CharField(default='(+229)0000000000', max_length=64),
        ),
    ]
