# Generated by Django 5.0.6 on 2024-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_remove_novel_image_url_alter_novel_novel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelimage',
            name='image_url',
            field=models.CharField(default='/static/novel/imgs/', max_length=256),
        ),
    ]
