# Generated by Django 5.0.6 on 2024-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_alter_novelimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelimage',
            name='image_url',
            field=models.CharField(max_length=256),
        ),
    ]
