# Generated by Django 5.0.6 on 2024-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_alter_novelimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
