# Generated by Django 5.0.6 on 2024-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_remove_country_name_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
