# Generated by Django 5.0.6 on 2024-09-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_alter_country_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_code',
        ),
    ]
